example_project/apps/news/urls.py
"""URLs used by the CMS news app."""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ArticleArchiveView.as_view(), name='article_archive'),
    url(r'^feed/$', views.ArticleFeedView.as_view(), name='article_feed'),
    url(r'^(?P<slug>[^/]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
]

example_project/urls.py
from cms.forms import CMSPasswordChangeForm
from cms.sitemaps import registered_sitemaps
from cms.views import TextTemplateView
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.contenttypes import views as contenttypes_views
from django.contrib.sitemaps import views as sitemaps_views
from django.views import generic

from .apps.sections.models import sections_js
from .utils.views import FrontendView

admin.autodiscover()


urlpatterns = [

    # Admin URLs.
    url(r'^admin/password_change/$', auth_views.password_change,
        {'password_change_form': CMSPasswordChangeForm}, name='password_change'),
    url(r'^admin/password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include('social_django.urls', namespace='social')),
    url(r'^admin/pages/page/sections.js$', sections_js, name='admin_sections_js'),

    # Permalink redirection service.
    url(r'^r/(?P<content_type_id>\d+)-(?P<object_id>[^/]+)/$', contenttypes_views.shortcut, name='permalink_redirect'),

    url(r'^assets/', include('django_lazy_image.urls', namespace='assets')),

    # Google sitemap service.
    url(r'^sitemap.xml$', sitemaps_views.index, {'sitemaps': registered_sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': registered_sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Basic robots.txt.
    url(r'^robots.txt$', TextTemplateView.as_view(template_name='robots.txt')),

    # There's no favicon here!
    url(r'^favicon.ico$', generic.RedirectView.as_view(permanent=True)),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)


if settings.DEBUG:
    urlpatterns += [
        url(r'^404/$', generic.TemplateView.as_view(template_name='404.html')),
        url(r'^500/$', generic.TemplateView.as_view(template_name='500.html')),
        url(r'^frontend/$', FrontendView.as_view()),
        url(r'^frontend/(?P<slug>[\w-]+)/$', FrontendView.as_view())
    ]


handler500 = 'cms.views.handler500'

example_project/apps/components/models.py
from cms.apps.pages.models import Page
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.functional import cached_property


class CallToAction(models.Model):

    kicker = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    title = models.CharField(
        max_length=140
    )

    link_text = models.CharField(
        max_length=100,
    )

    link_page = models.ForeignKey(
        Page,
        blank=True,
        null=True,
        help_text='If you want to link to an internal page, please use this.',
    )

    link_url = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.',
    )

    def __str__(self):
        return self.title

    def clean(self):
        if not self.link_page and not self.link_url:
            raise ValidationError({
                'link_page': 'Please supply 1 of "link page" or "link URL"',
            })

    @property
    def has_link(self):
        return self.link_location and self.link_text

    @cached_property
    def link_location(self):
        try:
            return self.link_page.get_absolute_url() if self.link_page else self.link_url
        except (Page.DoesNotExist, AttributeError):
            return self.link_url

example_project/apps/redirects/models.py
import re

from django.db import models
from django.utils.safestring import mark_safe


class Redirect(models.Model):

    old_path = models.CharField(
        'redirect from',
        max_length=200,
        db_index=True,
        unique=True,
        help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'."
    )

    new_path = models.CharField(
        'redirect to',
        max_length=200,
        blank=True,
        help_text="This can be either an absolute path (as above) or a full URL starting with 'http://'."
    )

    regular_expression = models.BooleanField(
        default=False,
        help_text=mark_safe(
            "This will allow using regular expressions to match and "
            "replace patterns in URLs. See the "
            "<a href='https://docs.python.org/2/library/re.html' target='_blank'>Python "
            "regular expression documentation</a> for details."
        )
    )

    test_path = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        help_text=(
            "You will need to specify a test path to ensure your regular "
            "expression is valid."
        ),
    )

    class Meta:
        verbose_name = 'redirect'
        verbose_name_plural = 'redirects'
        ordering = ('old_path',)

    def __str__(self):
        return self.old_path

    def sub_path(self, path):
        """ If this redirect is a regular expression, it will return a
        rewritten version of `path`; otherwise returns the `new_path`. """
        if not self.regular_expression:
            return self.new_path
        return re.sub(self.old_path, self.new_path, path)

example_project/apps/site/models.py
from cms.apps.pages.models import Page
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.functional import cached_property


class Footer(models.Model):

    about_title = models.CharField(
        verbose_name='Title',
        max_length=50,
        blank=True,
        null=True,
    )

    about_text = models.TextField(
        max_length=400,
        verbose_name='Text',
        blank=True,
        null=True,
    )

    links_title = models.CharField(
        verbose_name='Title',
        max_length=50,
        blank=True,
        null=True,
    )

    contact_title = models.CharField(
        verbose_name='Title',
        max_length=50,
        blank=True,
        null=True,
    )

    contact_address = models.TextField(
        max_length=200,
        blank=True,
        null=True,
    )

    contact_link_text = models.CharField(
        verbose_name='Link text',
        max_length=50,
        blank=True,
        null=True,
    )

    contact_link_page = models.ForeignKey(
        'pages.Page',
        verbose_name='Link page',
        blank=True,
        null=True,
        related_name='+',
        help_text='If you want to link to an internal page, please use this.',
    )

    contact_link_url = models.CharField(
        verbose_name='Link URL',
        max_length=200,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.',
    )

    terms_of_use_text = models.CharField(
        verbose_name='Text',
        max_length=255,
        blank=True,
        null=True,
        default='Terms of use',
    )

    terms_of_use_page = models.ForeignKey(
        'pages.Page',
        blank=True,
        null=True,
        related_name='+',
        help_text='If you want to link to an internal page, please use this.',
    )

    terms_of_use_url = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.',
    )

    legal_text = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        default='Legal',
    )

    legal_page = models.ForeignKey(
        'pages.Page',
        blank=True,
        null=True,
        related_name='+',
        help_text='If you want to link to an internal page, please use this.',
    )

    legal_url = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.',
    )

    privacy_policy_text = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        default='Privacy Policy',
    )

    privacy_policy_page = models.ForeignKey(
        'pages.Page',
        blank=True,
        null=True,
        related_name='+',
        help_text='If you want to link to an internal page, please use this.',
    )

    privacy_policy_url = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.',
    )

    def __str__(self):
        return 'Footer'

    @property
    def contact_has_link(self):
        return self.contact_link_location and self.contact_link_text

    @cached_property
    def contact_link_location(self):
        try:
            return self.contact_link_page.get_absolute_url() if self.contact_link_page else self.contact_link_url
        except (Page.DoesNotExist, AttributeError):
            return self.contact_link_url

    @cached_property
    def extra_links(self):
        return {
            'terms': {
                'label': self.terms_of_use_text,
                'has_link': self.terms_of_use_location and self.terms_of_use_text,
                'link_location': self.terms_of_use_location,
            },
            'legal': {
                'label': self.legal_text,
                'has_link': self.legal_location and self.legal_text,
                'link_location': self.legal_location,
            },
            'privacy': {
                'label': self.privacy_policy_text,
                'has_link': self.privacy_policy_location and self.privacy_policy_text,
                'link_location': self.privacy_policy_location,
            },
        }

    @cached_property
    def terms_of_use_location(self):
        try:
            return self.terms_of_use_page.get_absolute_url() if self.terms_of_use_page else self.terms_of_use_url
        except (Page.DoesNotExist, AttributeError):
            return self.terms_of_use_url

    @cached_property
    def legal_location(self):
        try:
            return self.legal_page.get_absolute_url() if self.legal_page else self.legal_url
        except (Page.DoesNotExist, AttributeError):
            return self.legal_url

    @cached_property
    def privacy_policy_location(self):
        try:
            return self.privacy_policy_page.get_absolute_url() if self.privacy_policy_page else self.privacy_policy_url
        except (Page.DoesNotExist, AttributeError):
            return self.privacy_policy_url

    @cached_property
    def columns(self):
        return {
            'about': self.about_title and self.about_text,
            'links': self.links_title and self.footerlink_set.count(),
            'contact': self.contact_title and self.contact_address,
        }


class FooterLink(models.Model):

    footer = models.ForeignKey(
        'site.Footer',
    )

    text = models.CharField(
        max_length=100,
    )

    link_page = models.ForeignKey(
        'pages.Page',
        blank=True,
        null=True,
        help_text='If you want to link to an internal page, please use this.',
        related_name='+'
    )

    link_url = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.'
    )

    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.text

    def clean(self):
        if self.link_page or self.link_url:
            pass
        else:
            raise ValidationError({
                'link_page': 'Please supply either a link page or a link url.'
            })

    def has_link(self):
        return self.link_location and self.text

    @cached_property
    def link_location(self):
        if self.link_page_id:
            try:
                return self.link_page.get_absolute_url()
            except Page.DoesNotExist:
                pass
        return self.link_url


class Header(models.Model):

    show_search = models.BooleanField(
        default=True
    )

    def __str__(self):
        return 'Header'


class HeaderLink(models.Model):

    header = models.ForeignKey(
        'site.Header',
    )

    link_text = models.CharField(
        max_length=100,
    )

    link_page = models.ForeignKey(
        'pages.Page',
        blank=True,
        null=True,
        help_text='If you want to link to an internal page, please use this.',
        related_name='+'
    )

    link_url = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='If you want to link to an external page, please use this.'
    )

    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.link_text

    def clean(self):
        if self.link_page or self.link_url:
            pass
        else:
            raise ValidationError({
                'link_page': 'Please supply either a link page or a link url.'
            })

    def has_link(self):
        return self.link_location and self.link_text

    @cached_property
    def link_location(self):
        if self.link_page_id:
            try:
                return self.link_page.get_absolute_url()
            except Page.DoesNotExist:
                pass
        return self.link_url

example_project/apps/news/views.py
"""Views used by the CMS news app."""

from cms.html import process as process_html
from cms.views import SearchMetaDetailMixin
from django.http import HttpResponse
from django.utils.feedgenerator import DefaultFeed
from django.views.generic import DetailView, ListView
from django.views.generic.list import BaseListView

from .models import Article, Category


class ArticleMixin(object):
    model = Article

    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleMixin, self).get_context_data(**kwargs)
        category_list = Category.objects.filter(
            article__news_feed__page=self.request.pages.current
        ).distinct()
        context['category_list'] = category_list

        return context


class ArticleListMixin(ArticleMixin):
    make_object_list = True

    allow_empty = True

    context_object_name = 'article_list'

    def get_paginate_by(self, queryset):
        return self.request.pages.current.content.per_page

    def get_queryset(self):
        return super(ArticleListMixin, self).get_queryset().prefetch_related(
            'categories',
        ).select_related(
            'image',
            'card_image',
        ).filter(
            news_feed__page=self.request.pages.current,
        ).order_by(
            '-date'
        )


class ArticleArchiveView(ArticleListMixin, ListView):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.featured_article = None

    def dispatch(self, request, *args, **kwargs):
        self.featured_article = Article.objects.filter(featured=True)[:1].get()

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super().get_queryset().exclude(id=self.featured_article.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['featured_article'] = self.featured_article

        return context


class ArticleFeedView(ArticleListMixin, BaseListView):
    def get(self, request, *args, **kwargs):
        """Generates the RSS feed."""
        page = request.pages.current

        # Write the feed headers.
        feed = DefaultFeed(
            title=page.title,
            link=page.get_absolute_url(),
            description=page.meta_description,
        )

        # Write the feed items.
        for article in self.get_queryset()[:30]:
            feed.add_item(
                title=article.title,
                link=article.get_absolute_url(),
                description=process_html(
                    article.summary or article.content),
                pubdate=article.date,
            )

        # Write the response.
        content = feed.writeString('utf-8')
        response = HttpResponse(content)
        response['Content-Type'] = feed.mime_type
        response['Content-Length'] = len(content)

        return response


class ArticleDetailView(ArticleMixin, SearchMetaDetailMixin, DetailView):
    pass

example_project/utils/views.py
from django.views.generic import TemplateView


class FrontendView(TemplateView):
    def get_template_names(self):
        # If no slug exists just serve the base so we can access the template switcher
        template_name = self.kwargs.get('slug', '_base')

        return ['frontend/{}.html'.format(template_name)]

example_project/templates/base/_analytics.html
{% if settings.GOOGLE_ANALYTICS %}
  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', '{{ settings.GOOGLE_ANALYTICS }}', 'auto');
    ga('send', 'pageview');
  </script>
{% endif %}

example_project/templates/base/_browser-update.html
<script>
  var $buoop = {c: 2};
  function $buo_f() {
    var e = document.createElement("script");
    e.src = "//browser-update.org/update.js";
    document.body.appendChild(e);
  };
  try {document.addEventListener("DOMContentLoaded", $buo_f, false)}
  catch (e) {window.attachEvent("onload", $buo_f)}
</script>

example_project/templates/base/_favicons.html
<link rel="shortcut icon" href="{{ static('favicons/favicon.ico') }}" type="image/x-icon">
<link rel="apple-touch-icon" sizes="57x57" href="{{ static('favicons/apple-touch-icon-57x57.png') }}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ static('favicons/apple-touch-icon-60x60.png') }}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ static('favicons/apple-touch-icon-72x72.png') }}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ static('favicons/apple-touch-icon-76x76.png') }}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ static('favicons/apple-touch-icon-114x114.png') }}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ static('favicons/apple-touch-icon-120x120.png') }}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ static('favicons/apple-touch-icon-144x144.png') }}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ static('favicons/apple-touch-icon-152x152.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ static('favicons/apple-touch-icon-180x180.png') }}">
<link rel="icon" type="image/png" href="{{ static('favicons/favicon-16x16.png') }}" sizes="16x16">
<link rel="icon" type="image/png" href="{{ static('favicons/favicon-32x32.png') }}" sizes="32x32">
<link rel="icon" type="image/png" href="{{ static('favicons/favicon-96x96.png') }}" sizes="96x96">
<link rel="icon" type="image/png" href="{{ static('favicons/android-chrome-192x192.png') }}" sizes="192x192">

<meta name="msapplication-square70x70logo" content="{{ static('favicons/smalltile.png') }}">
<meta name="msapplication-square150x150logo" content="{{ static('favicons/mediumtile.png') }}">
<meta name="msapplication-wide310x150logo" content="{{ static('favicons/widetile.png') }}">
<meta name="msapplication-square310x310logo" content="{{ static('favicons/largetile.png') }}">

example_project/templates/base/_footer.html
{% set footer = get_footer_content() %}

{% if footer %}
  <footer class="ft-Footer">
    <div class="ft-Footer_Inner">
      <div class="ft-Footer_Body">
        <div class="ft-Footer_Columns">
          {% if footer.columns.about %}
            <div class="ft-Footer_Column ft-Footer_Column-about">
              <h4 class="ft-Footer_Title">{{ footer.about_title }}</h4>

              <p class="ft-Footer_Text">{{ footer.about_text | md(True) }}</p>
            </div>
          {% endif %}

          {% if footer.columns.links %}
            <div class="ft-Footer_Column ft-Footer_Column-links">
              <h4 class="ft-Footer_Title">{{ footer.links_title }}</h4>

              <ul class="ft-Footer_Links">
                {% for link in footer.footerlink_set.all() %}
                  <li class="ft-Footer_LinkItem">
                    <a class="ft-Footer_Link" href="{{ link.link_location }}">{{ link.text }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          {% endif %}

          {% if footer.columns.contact %}
            <div class="ft-Footer_Column ft-Footer_Column-contact">
              <h4 class="ft-Footer_Title">{{ footer.contact_title }}</h4>

              <address class="ft-Footer_Address">{{ footer.contact_address | linebreaksbr() }}</address>

              {% if footer.contact_has_link %}
                <a class="ft-Footer_Button btn-Primary"
                   href="{{ footer.contact_link_location }}">{{ footer.contact_link_text }}</a>
              {% endif %}
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </footer>

  <div class="ft-Bar">
    <div class="ft-Bar_Inner">
      <div class="ft-Bar_Body">
        <div class="ft-Bar_Left">
          <p class="ft-Bar_Copyright">
            Copyright © {% now "Y" %} {{ settings.SITE_NAME }}
          </p>

          {% set extra_links = footer.extra_links %}
          {% if extra_links.terms.has_link or extra_links.legal.has_link or extra_links.privacy.has_link %}
            <ul class="ft-Bar_Links">
              {% if extra_links.terms.has_link %}
                <li class="ft-Bar_LinksItem">
                  <a class="ft-Bar_Link"
                     href="{{ extra_links.terms.link_location }}">{{ extra_links.terms.label }}</a>
                </li>
              {% endif %}

              {% if extra_links.legal.has_link %}
                <li class="ft-Bar_LinksItem">
                  <a class="ft-Bar_Link"
                     href="{{ extra_links.legal.link_location }}">{{ extra_links.legal.label }}</a>
                </li>
              {% endif %}

              {% if extra_links.privacy.has_link %}
                <li class="ft-Bar_LinksItem">
                  <a class="ft-Bar_Link"
                     href="{{ extra_links.privacy.link_location }}">{{ extra_links.privacy.label }}</a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
        </div>

        <div class="ft-Bar_Right">
          <a class="ft-Bar_Onespacemedia" href="//onespacemedia.com">
            Designed and built by <strong>Onespacemedia</strong>
          </a>
        </div>
      </div>
    </div>
  </div>
{% endif %}

example_project/templates/base/_header.html
{% set header = get_header_content() %}
{% if header and header.headerlink_set.all() %}
  <div class="hd-Bar">
    <div class="hd-Bar_Inner">
      <div class="hd-Bar_Body">
        <ul class="hd-Bar_Items">
          {% for link in header.headerlink_set.all() %}
            <li class="hd-Bar_Item">
              <a class="hd-Bar_Link" href="{{ link.link_location }}">{{ link.link_text }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endif %}

<header class="hd-Header">
  <div class="hd-Header_Inner">
    <div class="hd-Header_Body">
      <a class="hd-Header_Logo" href="{{ pages.homepage.get_absolute_url() }}"></a>

      <div class="hd-Header_Nav">
        {{ render_navigation(pages.homepage.navigation, recursive=True) }}
      </div>
    </div>
  </div>
</header>

example_project/templates/base/_typekit.html
<script>
  if (window.localStorage && window.localStorage._tk_cache) {
    document.documentElement.classList.add('wf-active')
    var script = document.createElement('script')
    script.innerHTML = localStorage._tk_cache + ";(function () {var timeout = setTimeout(function () {document.documentElement.classList.remove('wf-active');}, 300); Typekit.load({ async: false, active: function () { clearTimeout(timeout); }});})();";
    document.head.appendChild(script);
  }
  window._tk_onload = function () {
    var req = new XMLHttpRequest()
    req.addEventListener("load", function () {
      window.localStorage._tk_cache = this.responseText;
    });
    req.open("GET", "https://use.typekit.net/{{ settings.TYPEKIT_KIT_ID }}.js");
    req.send();
  };
</script>

<script async
        src="https://use.typekit.net/{{ settings.TYPEKIT_KIT_ID }}.js"
        onload="Typekit.load({ async: true, loading: window._tk_onload })"></script>